### PR TITLE
DbtFolder parser: collect schema info for source tables

### PR DESCRIPTION
**Pull request by remigabillet**
New take on #24 since the underlying code changed so much since #24 was open.

### CODE REVIEW

**Comment by remigabillet** [comment]
@z3z1ma most of #24 was implemented in #19 so this PR is much smaller.

**Comment by z3z1ma** [comment]
Looking good @remigabillet thanks for rebasing. I will review more deeply this later today with any code comments (its a minor change so it wont be too bad). One question that came to mind right away that we already know, makes the folder parser a less robust option in comparison to manifest parsing, is a block like this (I personally use this in a production config). Let me know thoughts on this.

```
version: 2
sources:
- name: modelling
  schema: '{{ target.schema }}'
  loader: python
  loaded_at_field: model_ran_at
  tables:
  - name: fitness_model_3
    identifier: model_gen_f_daily
    description: '# Modelling data for Gen E -> Gen G Hydropanels using a linear model based on TMY solar data'

```

**Comment by remigabillet** [comment]
@z3z1ma Good question. I feel that handing jinja variable substitutions is beyond the scope for DbtFolder. It's inherently limited. At that point, the manifest file should be used.

**Review by z3z1ma — APPROVED** [review]
Looks good,
I think until we deprecate folder parser- something like this
```
if "{{" in source_schema_name  and "}}" in source_schema_name:
  logging.warning("dbt Folder Reader cannot resolve jinja expressions- use the Manifest Reader instead.")
``` 
could be useful for end users

We then have a choice to fail fast there or allow the processing to continue with the jinja source name which of course wont match to any schemas in Metabase and thus wont cause any harm (no risk really). 

Not needed in this PR, just a thought if you wanted to add. The next PR should include a deprecation message for folder reader.

**Review by z3z1ma — CHANGES_REQUESTED** [review]
Ah before we proceed, we need to make sure any call to `build_metadata_lookups` does not pass in schema as an arg. It is being passed in currently in the function calls.

**Comment by remigabillet** [comment]
@z3z1ma thanks for the suggestions!

**Comment by gouline** [comment]
Looks good to me, if @z3z1ma is happy then I'll merge.

**Comment by z3z1ma** [comment]
@gouline 

Yep, looks great. I will rebase my fork after this is implemented.

**Comment by remigabillet** [comment]
Thanks @gouline and @z3z1ma!

**Review by gouline — APPROVED** [review]

**Pull request merged**
